#! /bin/sh

setxkbmap -layout latam,us &
setxkbmap -option caps:swapescape &
setxkbmap -option grp:rctrl_toggle &
picom &
sleep 1 && ~/.screenlayout/mm.sh &
nitrogen --restore &
sleep 1 && ~/.config/polybar/launch.sh &
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor eDP-1 -d 6 7 8 9 0

bspc config focused_border_color "#DCD7BA"
bspc config normal_border_color "#0d0c0c"
bspc config active_border_color "#625E5A"
bspc config border_width 3
bspc config window_gap 6

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a polybar

bspc config top_padding 0
bspc config single_monocle true
bspc config gapless_monocle true
